"""BDM-v1 Scenario Family Generator v2 (Issue #72).

Deterministic generator for causally distinct Habitat V2 development families
with mechanism-held-out, group-disjoint custody partitions. A family scenario
is a pure function of ``(generator version, registry seed, group index,
sensor variant, feasibility attempt)``; identical inputs regenerate
byte-identical scenario JSON.

Design rules enforced here:

- Parameter draws come only from declared bands: generator-variable records of
  the Issue #71 provenance manifest plus the explicitly declared generator
  vocabularies in this module (fault multipliers/windows, sensor-defect
  magnitudes, initial oxygen regime bands). No undeclared knob exists.
- Grouping follows the Issue #70 contract: the causal group is the independent
  unit; paired sensor variants and every counterfactual branch of one causal
  starting state stay in the same group.
- Operating-mode labels are context only; every physical load or command
  change is explicit in the timeline.
- BLIND_FINAL families are generated by the same deterministic stream and are
  sealed by digest in the custody registry; no blind outcome is ever computed
  in development.

This module never runs the plant, trains a model, or opens blind outcomes.
HMC remains the sole proposal-arbitration, final-command, plant-step, and
replay authority in every downstream study.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import hashlib
import json
from pathlib import Path
from typing import Any, Mapping, Sequence

from .physics_provenance import (
    generator_variable_parameters,
    sample_band,
)
from .scenario import Scenario, ScenarioValidationError

GENERATOR_VERSION = "bdm_v1_family_generator_v1"
GENERATOR_REGISTRY_SEED = "bdm-v1-families-2026-09-05"
BASE_SCENARIO_RELATIVE_PATH = Path("scenarios/habitat_v2_forecast_development.json")

EPISODE_STEPS = 96
DT_SECONDS = 60.0
DECISION_START_STEP = 16
DECISION_CADENCE_STEPS = 4
RISK_HORIZON_STEPS = 32
DECISION_STEPS: tuple[int, ...] = tuple(
    step
    for step in range(DECISION_START_STEP, EPISODE_STEPS, DECISION_CADENCE_STEPS)
    if step + RISK_HORIZON_STEPS <= EPISODE_STEPS
)

SENSOR_SEED_BASE = 20260812
SENSOR_VARIANT_OFFSETS = (0, 17)
SENSOR_VARIANT_SUFFIXES = ("a", "b")

BDM_V1_PARTITIONS_ORDERED = ("TRAIN", "DEV", "CALIBRATION", "BLIND_FINAL")
DEFAULT_GROUPS_PER_PARTITION: Mapping[str, int] = {
    "TRAIN": 40,
    "DEV": 16,
    "CALIBRATION": 12,
    "BLIND_FINAL": 12,
}
MAX_FEASIBILITY_ATTEMPTS = 8

STRATA_ORDERED = (
    "useful_opportunity",
    "no_action",
    "sensor_failure",
    "actuator_failure",
    "compound",
)

PHYSICAL_FAULT_TYPES = (
    "fan_speed_degradation",
    "branch_resistance_increase",
    "cooling_delivery_degradation",
    "oxygen_delivery_degradation",
    "scrubber_effectiveness_degradation",
    "condenser_effectiveness_degradation",
)
ACTUATOR_FAULT_TYPES = ("damper_jam",)
SENSOR_DEFECT_TYPES = (
    "sensor_bias_drift",
    "sensor_stuck",
    "feedback_sensor_stuck",
)

# Declared generator vocabularies (stress-test class). These extend, never
# contradict, the Issue #71 manifest: the manifest governs fixture physics
# parameters, this table governs fault/sensor-defect shapes and the BDM
# initial-oxygen regime bands, which are new scenario content specific to the
# generator population.
GENERATOR_FAULT_MULTIPLIER_BANDS: Mapping[str, tuple[float, float]] = {
    "fan_speed_degradation": (0.80, 0.98),
    "branch_resistance_increase": (1.30, 3.00),
    "cooling_delivery_degradation": (0.65, 0.95),
    "oxygen_delivery_degradation": (0.65, 0.95),
    "scrubber_effectiveness_degradation": (0.50, 0.90),
    "condenser_effectiveness_degradation": (0.50, 0.90),
}
GENERATOR_FAULT_ONSET_CLASSES: Mapping[str, tuple[int, int]] = {
    "early": (8, 16),
    "in_window": (17, 48),
    "late": (49, 72),
}
GENERATOR_FAULT_DURATION_RANGE: tuple[int, int] = (16, 64)
GENERATOR_RAMP_SHAPES = ("worsening", "sustained", "recovery")
GENERATOR_SENSOR_BIAS_BANDS: Mapping[str, tuple[float, float]] = {
    "temperature_k": (0.3, 1.5),
    "pressure_pa": (150.0, 600.0),
    "co2_ppm": (25.0, 120.0),
    "o2_mole_fraction": (0.001, 0.004),
    "relative_humidity": (0.01, 0.05),
}
GENERATOR_SENSOR_CHANNELS = tuple(GENERATOR_SENSOR_BIAS_BANDS)
GENERATOR_SENSOR_HEADS = ("primary", "secondary")
GENERATOR_FEEDBACK_GAUGES = (
    ("battery_state_of_charge", "battery"),
    ("oxygen_store_fraction", "oxygen_store"),
    ("sorbent_remaining_fraction", "sorbent"),
)
GENERATOR_SENSOR_BUNDLE_KINDS = (
    "single_bias_drift",
    "dual_stuck_correlated",
    "feedback_gauge_defect",
    "mixed_bias_and_stuck",
)
# Initial oxygen regime bands. The Issue #71 manifest freezes the Issue
# 55/56 race fixtures at the 0.30 upper bound; the BDM population instead
# spans nominal air up to the bound so that no-action strata exist and the
# dormant/O2 pattern cannot dominate the corpus by construction.
GENERATOR_INITIAL_O2_BANDS: Mapping[str, tuple[float, float]] = {
    "low": (0.2095, 0.24),
    "high": (0.285, 0.30),
    "full": (0.2095, 0.30),
}
GENERATOR_O2_EXCESS_THRESHOLD = 0.285


class BdmV1FamilyError(ValueError):
    """Raised when family generation or custody assignment is invalid."""


@dataclass(frozen=True)
class TemplateSpec:
    template_id: str
    stratum: str
    schedule: str
    fault_kinds: tuple[str, ...]
    sensor_bundle_kinds: tuple[str, ...]
    o2_regime: str
    load_regime: str
    reserve_regime: str


TEMPLATES: tuple[TemplateSpec, ...] = (
    TemplateSpec("t01_healthy_steady", "no_action", "steady", (), ("none",), "low", "nominal", "nominal"),
    TemplateSpec("t02_o2_regime_stress", "useful_opportunity", "steady", (), ("none",), "high", "high", "nominal"),
    TemplateSpec("t03_fan_degradation", "useful_opportunity", "steady", ("fan_speed_degradation",), ("none",), "full", "nominal", "nominal"),
    TemplateSpec("t04_branch_resistance", "useful_opportunity", "steady", ("branch_resistance_increase",), ("none",), "full", "nominal", "nominal"),
    TemplateSpec("t05_cooling_delivery_loss", "useful_opportunity", "steady", ("cooling_delivery_degradation",), ("none",), "full", "nominal", "nominal"),
    TemplateSpec("t06_oxygen_delivery_loss", "useful_opportunity", "steady", ("oxygen_delivery_degradation",), ("none",), "full", "nominal", "nominal"),
    TemplateSpec("t07_scrubber_condenser_stress", "useful_opportunity", "steady", ("scrubber_effectiveness_degradation", "condenser_effectiveness_degradation"), ("none",), "full", "nominal", "nominal"),
    TemplateSpec("t08_sensor_defect_bundle", "sensor_failure", "steady", (), GENERATOR_SENSOR_BUNDLE_KINDS, "full", "nominal", "nominal"),
    TemplateSpec("t09_actuator_failure", "actuator_failure", "steady", ("damper_jam",), ("feedback_gauge_defect",), "full", "nominal", "nominal"),
    TemplateSpec("t10_compound_physical_sensor", "compound", "steady", ("fan_speed_degradation", "cooling_delivery_degradation"), GENERATOR_SENSOR_BUNDLE_KINDS, "full", "nominal", "nominal"),
    TemplateSpec("t11_low_reserve_depletion", "useful_opportunity", "steady", (), ("none",), "full", "nominal", "low"),
    TemplateSpec("t12_schedule_transition", "useful_opportunity", "transition", ("branch_resistance_increase",), ("none",), "full", "nominal", "nominal"),
)
TEMPLATE_BY_ID = {template.template_id: template for template in TEMPLATES}


@dataclass(frozen=True)
class GeneratorConfig:
    seed: str = GENERATOR_REGISTRY_SEED
    groups_per_partition: Mapping[str, int] = field(
        default_factory=lambda: dict(DEFAULT_GROUPS_PER_PARTITION)
    )
    max_feasibility_attempts: int = MAX_FEASIBILITY_ATTEMPTS


@dataclass(frozen=True)
class GroupPlan:
    group_index: int
    group_id: str
    template: TemplateSpec
    partition: str


@dataclass(frozen=True)
class FamilyDefinition:
    family_id: str
    group_id: str
    group_index: int
    partition: str
    sensor_variant: str
    template_id: str
    stratum: str
    attempt: int
    group_key: Mapping[str, str]
    parameter_draws: Mapping[str, float]
    generator_draws: Mapping[str, Any]
    sensor_seed: int
    scenario_sha256: str

    def to_mapping(self) -> dict[str, Any]:
        return {
            "family_id": self.family_id,
            "group_id": self.group_id,
            "group_index": self.group_index,
            "partition": self.partition,
            "sensor_variant": self.sensor_variant,
            "template_id": self.template_id,
            "stratum": self.stratum,
            "attempt": self.attempt,
            "group_key": dict(self.group_key),
            "parameter_draws": dict(self.parameter_draws),
            "generator_draws": json.loads(json.dumps(self.generator_draws, sort_keys=True)),
            "sensor_seed": self.sensor_seed,
            "scenario_sha256": self.scenario_sha256,
        }


def _unit(seed: str, stream: str, *parts: str | int) -> float:
    payload = "|".join((GENERATOR_VERSION, seed, stream, *(str(part) for part in parts)))
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    return int(digest[:16], 16) / float(1 << 64)


def _draw_int(seed: str, stream: str, low: int, high: int, *parts: str | int) -> int:
    if low > high:
        raise BdmV1FamilyError(f"integer draw band {low}..{high} is inverted")
    unit = _unit(seed, stream, *parts)
    return low + int(unit * (high - low + 1)) % (high - low + 1)


def _draw_float(seed: str, stream: str, low: float, high: float, *parts: str | int) -> float:
    if low > high:
        raise BdmV1FamilyError(f"float draw band {low}..{high} is inverted")
    return low + _unit(seed, stream, *parts) * (high - low)


def _pick(seed: str, stream: str, options: Sequence[Any], *parts: str | int) -> Any:
    if not options:
        raise BdmV1FamilyError("cannot pick from an empty option list")
    index = int(_unit(seed, stream, *parts) * len(options)) % len(options)
    return options[index]


def load_base_scenario_data(root: str | Path) -> tuple[dict[str, Any], str]:
    """Load the frozen base fixture and return its data and digest."""

    path = Path(root).resolve() / BASE_SCENARIO_RELATIVE_PATH
    try:
        raw = path.read_bytes()
    except OSError as error:
        raise BdmV1FamilyError("base scenario fixture is unreadable") from error
    data = json.loads(raw)
    if type(data) is not dict:
        raise BdmV1FamilyError("base scenario fixture must be a JSON object")
    return data, hashlib.sha256(raw).hexdigest()


def _copy_json(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _copy_json(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_copy_json(item) for item in value]
    return value


def total_groups(config: GeneratorConfig) -> int:
    unknown = set(config.groups_per_partition) - set(BDM_V1_PARTITIONS_ORDERED)
    if unknown:
        raise BdmV1FamilyError(f"unknown custody partitions {sorted(unknown)}")
    total = sum(int(count) for count in config.groups_per_partition.values())
    if total <= 0:
        raise BdmV1FamilyError("generator requires at least one group")
    return total


def _template_for_group(group_index: int) -> TemplateSpec:
    return TEMPLATES[group_index % len(TEMPLATES)]


def assign_partitions(config: GeneratorConfig) -> tuple[GroupPlan, ...]:
    """Deal groups into custody partitions, stratified and group-disjoint."""

    counts = {
        partition: int(config.groups_per_partition.get(partition, 0))
        for partition in BDM_V1_PARTITIONS_ORDERED
    }
    total = sum(counts.values())
    group_indices = list(range(total))
    # Deterministic shuffle of group indices within each template residue so
    # every stratum sees a seeded permutation rather than raw index order.
    order = sorted(
        group_indices,
        key=lambda index: (
            _unit(config.seed, "group-order", index),
            index,
        ),
    )
    by_stratum: dict[str, list[int]] = {stratum: [] for stratum in STRATA_ORDERED}
    for group_index in order:
        by_stratum[_template_for_group(group_index).stratum].append(group_index)

    assignment: dict[int, str] = {}
    remaining_counts = dict(counts)
    remaining_groups = total
    for stratum in STRATA_ORDERED:
        members = by_stratum[stratum]
        n_s = len(members)
        if n_s == 0:
            continue
        raw = {
            partition: n_s * remaining_counts[partition] / remaining_groups
            for partition in BDM_V1_PARTITIONS_ORDERED
        }
        floors = {partition: int(raw[partition] // 1) for partition in raw}
        for partition, floor_value in floors.items():
            if floor_value > remaining_counts[partition]:
                floors[partition] = remaining_counts[partition]
        assigned = sum(floors.values())
        leftover = n_s - assigned
        fractions = sorted(
            BDM_V1_PARTITIONS_ORDERED,
            key=lambda partition: (
                -(raw[partition] - floors[partition]),
                BDM_V1_PARTITIONS_ORDERED.index(partition),
            ),
        )
        cursor = 0
        while leftover > 0:
            partition = fractions[cursor % len(fractions)]
            cursor += 1
            if floors[partition] < remaining_counts[partition]:
                floors[partition] += 1
                leftover -= 1
            if cursor > 4 * len(fractions) and leftover > 0:
                raise BdmV1FamilyError("stratified partition deal cannot place a group")
        for partition in BDM_V1_PARTITIONS_ORDERED:
            remaining_counts[partition] -= floors[partition]
        remaining_groups -= n_s
        position = 0
        for partition in BDM_V1_PARTITIONS_ORDERED:
            for _ in range(floors[partition]):
                assignment[members[position]] = partition
                position += 1

    plans: list[GroupPlan] = []
    for group_index in range(total):
        template = _template_for_group(group_index)
        plans.append(
            GroupPlan(
                group_index=group_index,
                group_id=f"bdmv1g{group_index:04d}",
                template=template,
                partition=assignment[group_index],
            )
        )
    return tuple(plans)


def _draw_manifest_parameters(
    config: GeneratorConfig, plan: GroupPlan, attempt: int, manifest: Mapping[str, Any]
) -> dict[str, float]:
    draws: dict[str, float] = {}
    template = plan.template
    for record in generator_variable_parameters(manifest):
        pid = record["parameter_id"]
        if pid in (
            "operating_load_scale_band",
            "operating_generation_w_band",
            "operating_temperature_delta_band",
            "operating_co2_delta_band",
            "fault_window_steps",
            "fan_fault_multiplier",
            "branch_resistance_fault_multiplier",
            "cooling_fault_multiplier",
            "cooling_fault_resource_factor",
            # Per-zone timeline loads are scaled by the group-level load_scale
            # draw and the explicit schedule segments; the per-load records
            # remain declared bands for future generator revisions.
            "occupied_zone_co2_generation_mol_s",
            "occupied_zone_o2_consumption_mol_s",
            "occupied_zone_water_vapor_generation_mol_s",
            "occupied_zone_sensible_heat_w",
            "laboratory_zone_co2_generation_mol_s",
            "laboratory_zone_o2_consumption_mol_s",
            "equipment_bay_sensible_heat_w",
            # Sensor noise amplitudes are pinned by the reviewed HMC contract:
            # reset rejects scenarios whose noise does not match, so the
            # generator must never draw them. Sensor-defect diversity comes
            # from bias-drift/stuck profiles and the noise seed instead.
            "sensor_primary_noise_temperature_k",
            "sensor_primary_noise_pressure_pa",
            "sensor_primary_noise_co2_ppm",
            "sensor_primary_noise_o2_mole_fraction",
            "sensor_primary_noise_relative_humidity",
        ):
            # Race-fixture band records: the generator draws its own declared
            # schedules/faults instead; these manifest records stay bound to
            # the Issue 55/56 fixtures.
            continue
        fraction = 2.0 * _unit(config.seed, "parameter", plan.group_id, pid, attempt) - 1.0
        if pid == "base_load_w" and template.load_regime == "high":
            fraction = max(fraction, 0.6)
        if pid in (
            "initial_battery_energy_wh",
            "initial_oxygen_store_mol",
            "initial_co2_sorbent_mol",
        ) and template.reserve_regime == "low":
            fraction = min(fraction, -0.5)
        draws[pid] = float(sample_band(record, fraction))
    return draws


def _load_scale(config: GeneratorConfig, plan: GroupPlan, attempt: int) -> float:
    template = plan.template
    scale = _draw_float(config.seed, "load-scale", 0.75, 1.30, plan.group_id, attempt)
    if template.load_regime == "high":
        scale = max(scale, 1.15)
    return scale


def _generation_w(
    config: GeneratorConfig, plan: GroupPlan, attempt: int, segment_index: int
) -> float:
    return _draw_float(
        config.seed,
        "generation-w",
        3500.0,
        6000.0,
        plan.group_id,
        attempt,
        segment_index,
    )


def _initial_o2(config: GeneratorConfig, plan: GroupPlan, attempt: int) -> float:
    low, high = GENERATOR_INITIAL_O2_BANDS[plan.template.o2_regime]
    return _draw_float(config.seed, "initial-o2", low, high, plan.group_id, attempt)


def _fault_spec(
    config: GeneratorConfig,
    plan: GroupPlan,
    attempt: int,
    fault_kind: str,
    fault_index: int,
    zone_ids: Sequence[str],
    damper_ids: Sequence[str],
) -> dict[str, Any]:
    seed = config.seed
    key = (plan.group_id, attempt, fault_kind, fault_index)
    onset_class = _pick(seed, "fault-onset-class", tuple(GENERATOR_FAULT_ONSET_CLASSES), *key)
    onset_low, onset_high = GENERATOR_FAULT_ONSET_CLASSES[onset_class]
    onset = _draw_int(seed, "fault-onset", onset_low, onset_high, *key)
    duration_low, duration_high = GENERATOR_FAULT_DURATION_RANGE
    duration = _draw_int(seed, "fault-duration", duration_low, duration_high, *key)
    end_step = min(EPISODE_STEPS - 1, onset + duration)
    if end_step - onset < 8:
        end_step = min(EPISODE_STEPS - 1, onset + 8)
    shape = _pick(seed, "fault-shape", GENERATOR_RAMP_SHAPES, *key)
    profile: dict[str, Any] = {
        "id": f"bdmv1-{plan.group_id}-{fault_kind}-{fault_index}-a{attempt}",
        "type": fault_kind,
        "start_step": onset,
        "end_step": end_step,
        "onset_class": onset_class,
        "ramp_shape": shape,
    }
    if fault_kind == "damper_jam":
        profile["damper_id"] = _pick(seed, "fault-damper", tuple(damper_ids), *key)
        return profile
    band_low, band_high = GENERATOR_FAULT_MULTIPLIER_BANDS[fault_kind]
    multiplier = _draw_float(seed, "fault-multiplier", band_low, band_high, *key)
    if shape == "worsening":
        start_multiplier, end_multiplier = 1.0, multiplier
    elif shape == "recovery":
        start_multiplier, end_multiplier = multiplier, 1.0
    else:
        start_multiplier, end_multiplier = multiplier, multiplier
    profile["start_multiplier"] = start_multiplier
    profile["end_multiplier"] = end_multiplier
    if fault_kind in (
        "branch_resistance_increase",
        "cooling_delivery_degradation",
        "oxygen_delivery_degradation",
    ):
        profile["zone_id"] = _pick(seed, "fault-zone", tuple(zone_ids), *key)
    return profile


def _sensor_profiles(
    config: GeneratorConfig,
    plan: GroupPlan,
    attempt: int,
    bundle_kind: str,
    zone_ids: Sequence[str],
) -> list[dict[str, Any]]:
    if bundle_kind == "none":
        return []
    seed = config.seed
    key = (plan.group_id, attempt, bundle_kind)
    profiles: list[dict[str, Any]] = []
    onset = _draw_int(seed, "sensor-onset", 12, 56, *key)
    duration = _draw_int(seed, "sensor-duration", 20, 64, *key)
    end_step = min(EPISODE_STEPS - 1, onset + duration)
    channel = _pick(seed, "sensor-channel", GENERATOR_SENSOR_CHANNELS, *key)
    head = _pick(seed, "sensor-head", GENERATOR_SENSOR_HEADS, *key)
    zone = _pick(seed, "sensor-zone", tuple(zone_ids), *key)
    if bundle_kind == "single_bias_drift":
        low, high = GENERATOR_SENSOR_BIAS_BANDS[channel]
        magnitude = _draw_float(seed, "sensor-bias", low, high, *key)
        sign = 1.0 if _unit(seed, "sensor-bias-sign", *key) < 0.5 else -1.0
        drift_end = -sign * magnitude if _unit(seed, "sensor-bias-flip", *key) < 0.5 else sign * magnitude
        profiles.append(
            {
                "id": f"bdmv1-{plan.group_id}-bias-{channel}-a{attempt}",
                "type": "sensor_bias_drift",
                "zone_id": zone,
                "sensor_head": head,
                "channel": channel,
                "start_step": onset,
                "end_step": end_step,
                "start_bias": sign * magnitude,
                "end_bias": drift_end,
            }
        )
    elif bundle_kind == "dual_stuck_correlated":
        others = tuple(zone_id for zone_id in zone_ids if zone_id != zone)
        second_zone = _pick(seed, "sensor-second-zone", others, *key)
        for index, stuck_zone in enumerate((zone, second_zone)):
            profiles.append(
                {
                    "id": f"bdmv1-{plan.group_id}-stuck-{channel}-{index}-a{attempt}",
                    "type": "sensor_stuck",
                    "zone_id": stuck_zone,
                    "sensor_head": head,
                    "channel": channel,
                    "start_step": onset,
                    "end_step": end_step,
                }
            )
    elif bundle_kind == "feedback_gauge_defect":
        gauge_channel, gauge_resource = _pick(
            seed, "feedback-gauge", GENERATOR_FEEDBACK_GAUGES, *key
        )
        profiles.append(
            {
                "id": f"bdmv1-{plan.group_id}-feedback-stuck-a{attempt}",
                "type": "feedback_sensor_stuck",
                "resource_id": gauge_resource,
                "channel": gauge_channel,
                "start_step": onset,
                "end_step": end_step,
            }
        )
    elif bundle_kind == "mixed_bias_and_stuck":
        low, high = GENERATOR_SENSOR_BIAS_BANDS[channel]
        magnitude = _draw_float(seed, "sensor-bias", low, high, *key)
        profiles.append(
            {
                "id": f"bdmv1-{plan.group_id}-bias-{channel}-a{attempt}",
                "type": "sensor_bias_drift",
                "zone_id": zone,
                "sensor_head": head,
                "channel": channel,
                "start_step": onset,
                "end_step": end_step,
                "start_bias": magnitude,
                "end_bias": magnitude,
            }
        )
        second_channel = _pick(
            seed,
            "sensor-second-channel",
            tuple(item for item in GENERATOR_SENSOR_CHANNELS if item != channel),
            *key,
        )
        stuck_onset = _draw_int(seed, "sensor-stuck-onset", onset, max(onset, end_step - 8), *key)
        profiles.append(
            {
                "id": f"bdmv1-{plan.group_id}-stuck-{second_channel}-a{attempt}",
                "type": "sensor_stuck",
                "zone_id": zone,
                "sensor_head": head,
                "channel": second_channel,
                "start_step": stuck_onset,
                "end_step": end_step,
            }
        )
    else:
        raise BdmV1FamilyError(f"unknown sensor bundle kind {bundle_kind!r}")
    return profiles


def _timeline(
    config: GeneratorConfig,
    plan: GroupPlan,
    attempt: int,
    base_timeline: Sequence[Mapping[str, Any]],
    load_scale: float,
) -> list[dict[str, Any]]:
    prototype = base_timeline[0]
    if plan.template.schedule == "steady":
        segments = [
            {
                "start_step": 0,
                "end_step": EPISODE_STEPS,
                "operating_mode": "occupied",
                "generation_w": _generation_w(config, plan, attempt, 0),
                "command": _copy_json(prototype["command"]),
                "loads": _copy_json(prototype["loads"]),
            }
        ]
    elif plan.template.schedule == "transition":
        modes = ("occupied", "eva_transition", "contingency")
        scales = (1.0, 0.75, 1.2)
        segments = []
        for index, (mode, scale) in enumerate(zip(modes, scales)):
            start = index * 32
            segments.append(
                {
                    "start_step": start,
                    "end_step": start + 32,
                    "operating_mode": mode,
                    "generation_w": _generation_w(config, plan, attempt, index),
                    "command": _copy_json(prototype["command"]),
                    "loads": _copy_json(prototype["loads"]),
                }
            )
        for segment in segments:
            scale = scales[segment["start_step"] // 32]
            for zone_loads in segment["loads"].values():
                for field in (
                    "co2_generation_mol_s",
                    "o2_consumption_mol_s",
                    "sensible_heat_w",
                    "water_vapor_generation_mol_s",
                ):
                    zone_loads[field] = float(zone_loads[field]) * scale
    else:
        raise BdmV1FamilyError(f"unknown schedule {plan.template.schedule!r}")
    if plan.template.schedule == "steady":
        for zone_loads in segments[0]["loads"].values():
            for field in (
                "co2_generation_mol_s",
                "o2_consumption_mol_s",
                "sensible_heat_w",
                "water_vapor_generation_mol_s",
            ):
                zone_loads[field] = float(zone_loads[field]) * load_scale
    else:
        for segment in segments:
            for zone_loads in segment["loads"].values():
                for field in (
                    "co2_generation_mol_s",
                    "o2_consumption_mol_s",
                    "sensible_heat_w",
                    "water_vapor_generation_mol_s",
                ):
                    zone_loads[field] = float(zone_loads[field]) * load_scale
    return segments


def _apply_parameter_draws(data: dict[str, Any], draws: Mapping[str, float]) -> None:
    equipment = data["equipment"]
    for key in (
        "air_density_kg_m3",
        "base_load_w",
        "battery_capacity_wh",
        "condenser_max_water_mol_s",
        "cooling_coefficient_of_performance",
        "cooling_max_thermal_w_per_zone",
        "oxygen_injection_max_total_mol_s",
        "scrubber_capacity_mol",
        "scrubber_max_co2_mol_s",
    ):
        if key in draws:
            equipment[key] = draws[key]
    initial_utility = data["initial_utility"]
    utility_map = {
        "initial_battery_energy_wh": "battery_energy_wh",
        "initial_oxygen_store_mol": "oxygen_store_mol",
        "initial_co2_sorbent_mol": "co2_sorbent_remaining_mol",
    }
    for pid, key in utility_map.items():
        if pid in draws:
            value = float(draws[pid])
            if key == "co2_sorbent_remaining_mol":
                value = min(value, float(equipment["scrubber_capacity_mol"]))
            if key == "battery_energy_wh":
                value = min(value, float(equipment["battery_capacity_wh"]))
            initial_utility[key] = value
    network = data["air_network"]
    fan_map = {
        "fan_rated_free_delivery_m3_s": "rated_free_delivery_m3_s",
        "fan_rated_shutoff_pressure_pa": "rated_shutoff_pressure_pa",
        "fan_total_efficiency": "total_efficiency",
    }
    for pid, key in fan_map.items():
        if pid in draws:
            network["fan"][key] = draws[pid]
    if "branch_open_supply_resistance_pa_s2_m6" in draws:
        for branch in network["branches"]:
            branch["open_supply_resistance_pa_s2_m6"] = draws[
                "branch_open_supply_resistance_pa_s2_m6"
            ]
    if "branch_return_resistance_pa_s2_m6" in draws:
        for branch in network["branches"]:
            branch["return_resistance_pa_s2_m6"] = draws["branch_return_resistance_pa_s2_m6"]
    if "damper_leak_fraction" in draws:
        for branch in network["branches"]:
            branch["damper_leak_fraction"] = draws["damper_leak_fraction"]
    shared = network["shared_resistance"]
    if "shared_supply_trunk_resistance_pa_s2_m6" in draws:
        shared["supply_trunk_pa_s2_m6"] = draws["shared_supply_trunk_resistance_pa_s2_m6"]
    zone_draws = {
        "zone_volume_m3": "volume_m3",
        "zone_thermal_capacity_j_per_k": "thermal_capacity_j_per_k",
        "passive_thermal_conductance_w_per_k": "passive_thermal_conductance_w_per_k",
        "sink_temperature_k": "sink_temperature_k",
    }
    initial_draws = {
        "initial_pressure_pa": "pressure_pa",
        "initial_co2_ppm": "co2_ppm",
        "initial_relative_humidity": "relative_humidity",
        "initial_temperature_k": "temperature_k",
    }
    for zone in data["zones"]:
        for pid, key in zone_draws.items():
            if pid in draws:
                zone[key] = draws[pid]
        for pid, key in initial_draws.items():
            if pid in draws:
                zone["initial"][key] = draws[pid]


def build_family_data(
    config: GeneratorConfig,
    plan: GroupPlan,
    variant_index: int,
    attempt: int,
    base_data: Mapping[str, Any],
    manifest: Mapping[str, Any],
    *,
    suppress_physical_faults: bool = False,
) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    """Build one family scenario mapping plus its recorded draws."""

    if variant_index not in (0, 1):
        raise BdmV1FamilyError("family generator supports exactly two sensor variants")
    if attempt < 0 or attempt >= config.max_feasibility_attempts:
        raise BdmV1FamilyError("feasibility attempt counter out of bounds")
    template = plan.template
    data = _copy_json(base_data)
    zone_ids = tuple(zone["id"] for zone in data["zones"])
    damper_ids = tuple(branch["damper_id"] for branch in data["air_network"]["branches"])

    draws = _draw_manifest_parameters(config, plan, attempt, manifest)
    _apply_parameter_draws(data, draws)
    load_scale = _load_scale(config, plan, attempt)
    initial_o2 = _initial_o2(config, plan, attempt)
    for zone in data["zones"]:
        zone["initial"]["o2_mole_fraction"] = initial_o2

    data["steps"] = EPISODE_STEPS
    data["dt_seconds"] = DT_SECONDS
    data["timeline"] = _timeline(config, plan, attempt, data["timeline"], load_scale)

    fault_profiles: list[dict[str, Any]] = []
    fault_metadata: list[dict[str, str]] = []
    first_onset_class = "none"
    effective_fault_kinds = () if suppress_physical_faults else template.fault_kinds
    for fault_index, fault_kind in enumerate(effective_fault_kinds):
        spec = _fault_spec(
            config, plan, attempt, fault_kind, fault_index, zone_ids, damper_ids
        )
        onset_class = str(spec.pop("onset_class"))
        ramp_shape = str(spec.pop("ramp_shape"))
        fault_profiles.append(spec)
        fault_metadata.append(
            {
                "type": fault_kind,
                "onset_class": onset_class,
                "ramp_shape": ramp_shape,
            }
        )
        if fault_index == 0:
            first_onset_class = onset_class
    bundle_kind = template.sensor_bundle_kinds[0]
    if len(template.sensor_bundle_kinds) > 1:
        bundle_kind = _pick(
            config.seed,
            "sensor-bundle",
            template.sensor_bundle_kinds,
            plan.group_id,
            attempt,
        )
    sensor_profiles = _sensor_profiles(config, plan, attempt, bundle_kind, zone_ids)
    data["fault_profiles"] = fault_profiles + sensor_profiles

    data["sensor_model"]["random_seed"] = (
        SENSOR_SEED_BASE + plan.group_index * 1000 + SENSOR_VARIANT_OFFSETS[variant_index]
    )
    data["name"] = (
        f"bdm-v1-{plan.group_id}-{SENSOR_VARIANT_SUFFIXES[variant_index]}-"
        f"{template.template_id}-a{attempt}"
    )

    if effective_fault_kinds:
        opportunity_id = f"fault_{first_onset_class}"
    elif initial_o2 >= GENERATOR_O2_EXCESS_THRESHOLD:
        opportunity_id = "o2_excess_from_start"
    else:
        opportunity_id = "no_opportunity"
    mechanism_id = "+".join(sorted(fault["type"] for fault in fault_profiles)) or "none"

    severity_values: list[float] = []
    if template.fault_kinds:
        for fault in fault_profiles:
            if "start_multiplier" not in fault:
                continue
            band_low, band_high = GENERATOR_FAULT_MULTIPLIER_BANDS[fault["type"]]
            worst = min(float(fault["start_multiplier"]), float(fault["end_multiplier"]))
            if band_high > 1.0:
                worst = max(float(fault["start_multiplier"]), float(fault["end_multiplier"]))
                severity = (worst - 1.0) / (band_high - 1.0)
            else:
                severity = (1.0 - worst) / (1.0 - band_low)
            severity_values.append(severity)
    load_norm = (load_scale - 0.75) / 0.55
    stress = 0.5 * load_norm + (0.5 * (sum(severity_values) / len(severity_values)) if severity_values else 0.0)
    param_band_id = "stress_low" if stress < 1.0 / 3.0 else ("stress_mid" if stress < 2.0 / 3.0 else "stress_high")

    generator_draws: dict[str, Any] = {
        "load_scale": load_scale,
        "initial_o2_mole_fraction": initial_o2,
        "initial_o2_regime": template.o2_regime,
        "reserve_regime": template.reserve_regime,
        "generation_w_by_segment": [
            float(segment["generation_w"]) for segment in data["timeline"]
        ],
        "sensor_bundle_kind": bundle_kind,
        "fault_mechanisms": fault_metadata,
        "fault_profiles": _copy_json(fault_profiles),
        "sensor_defect_profiles": _copy_json(sensor_profiles),
        "fault_ramp_shapes_declared": list(GENERATOR_RAMP_SHAPES),
    }
    group_key = {
        "causal_scenario_template": template.template_id,
        "physical_parameter_band": param_band_id,
        "fault_mechanism_composition": mechanism_id,
        "operating_schedule": template.schedule,
        "action_opportunity": opportunity_id,
        "sensor_failure_bundle": bundle_kind,
    }
    return data, group_key, generator_draws | {"parameter_draws": dict(draws)}


def scenario_digest(scenario_data: Mapping[str, Any]) -> str:
    payload = json.dumps(scenario_data, sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def build_matched_pair(
    config: GeneratorConfig,
    plan: GroupPlan,
    variant_index: int,
    attempt: int,
    base_data: Mapping[str, Any],
    manifest: Mapping[str, Any],
) -> tuple[dict[str, Any], dict[str, Any], tuple[str, ...]]:
    """Build the fault and healthy twins of one causal starting state.

    Both scenarios share every draw (identical seed streams); only the
    declared treatment field ``fault_profiles`` differs. The returned paths
    are the complete top-level diff, which tests and downstream checks
    assert against.
    """

    if not plan.template.fault_kinds:
        raise BdmV1FamilyError("matched pair requires a template with physical faults")
    fault_data, _, _ = build_family_data(
        config, plan, variant_index, attempt, base_data, manifest
    )
    healthy_data, _, _ = build_family_data(
        config,
        plan,
        variant_index,
        attempt,
        base_data,
        manifest,
        suppress_physical_faults=True,
    )
    return fault_data, healthy_data, ("fault_profiles",)


def build_family(
    config: GeneratorConfig,
    plan: GroupPlan,
    variant_index: int,
    attempt: int,
    base_data: Mapping[str, Any],
    manifest: Mapping[str, Any],
) -> tuple[FamilyDefinition, Scenario]:
    """Build and schema-validate one family; return its definition and scenario."""

    data, group_key, generator_draws = build_family_data(
        config, plan, variant_index, attempt, base_data, manifest
    )
    try:
        scenario = Scenario.from_mapping(data)
    except ScenarioValidationError as error:
        raise BdmV1FamilyError(
            f"generated family scenario failed schema validation: {error}"
        ) from error
    family_id = (
        f"bdm-v1-f{plan.group_index * 2 + variant_index:04d}-"
        f"{SENSOR_VARIANT_SUFFIXES[variant_index]}"
    )
    definition = FamilyDefinition(
        family_id=family_id,
        group_id=plan.group_id,
        group_index=plan.group_index,
        partition=plan.partition,
        sensor_variant=SENSOR_VARIANT_SUFFIXES[variant_index],
        template_id=plan.template.template_id,
        stratum=plan.template.stratum,
        attempt=attempt,
        group_key=group_key,
        parameter_draws=generator_draws.pop("parameter_draws"),
        generator_draws=generator_draws,
        sensor_seed=int(data["sensor_model"]["random_seed"]),
        scenario_sha256=scenario_digest(data),
    )
    return definition, scenario


def generate_families(
    config: GeneratorConfig,
    base_data: Mapping[str, Any],
    manifest: Mapping[str, Any],
) -> tuple[FamilyDefinition, ...]:
    """Generate every family of the roster (both sensor variants per group)."""

    plans = assign_partitions(config)
    families: list[FamilyDefinition] = []
    for plan in plans:
        for variant_index in (0, 1):
            definition, _scenario = build_family(
                config, plan, variant_index, 0, base_data, manifest
            )
            families.append(definition)
    return tuple(families)


def family_partition_groups(
    families: Sequence[FamilyDefinition],
) -> dict[str, list[str]]:
    """Group ids by partition, ready for the contract disjointness validator."""

    result: dict[str, list[str]] = {
        partition: [] for partition in BDM_V1_PARTITIONS_ORDERED
    }
    for family in families:
        if family.group_id not in result[family.partition]:
            result[family.partition].append(family.group_id)
    return {partition: sorted(groups) for partition, groups in result.items()}


__all__ = [
    "BDM_V1_PARTITIONS_ORDERED",
    "BASE_SCENARIO_RELATIVE_PATH",
    "DECISION_STEPS",
    "DT_SECONDS",
    "EPISODE_STEPS",
    "GENERATOR_FAULT_MULTIPLIER_BANDS",
    "GENERATOR_INITIAL_O2_BANDS",
    "GENERATOR_O2_EXCESS_THRESHOLD",
    "GENERATOR_REGISTRY_SEED",
    "GENERATOR_SENSOR_BIAS_BANDS",
    "GENERATOR_SENSOR_BUNDLE_KINDS",
    "GENERATOR_VERSION",
    "BdmV1FamilyError",
    "DEFAULT_GROUPS_PER_PARTITION",
    "FamilyDefinition",
    "GeneratorConfig",
    "GroupPlan",
    "MAX_FEASIBILITY_ATTEMPTS",
    "PHYSICAL_FAULT_TYPES",
    "SENSOR_DEFECT_TYPES",
    "STRATA_ORDERED",
    "TEMPLATES",
    "TemplateSpec",
    "assign_partitions",
    "build_family",
    "build_family_data",
    "build_matched_pair",
    "family_partition_groups",
    "generate_families",
    "load_base_scenario_data",
    "scenario_digest",
    "total_groups",
]
